namespace EventHorizon.Zone.System.ArtifactManagement.Model;

public static class ArtifactManagementSystemErrorCodes
{
    public const string ARTIFACT_MANAGEMENT_BACKUP_STEP_CREATE_DESTINATION_FAILED = nameof(ARTIFACT_MANAGEMENT_BACKUP_STEP_CREATE_DESTINATION_FAILED);
    public const string ARTIFACT_MANAGEMENT_BACKUP_STEP_DELETE_EXISTING_BACKUPS_FAILED = nameof(ARTIFACT_MANAGEMENT_BACKUP_STEP_DELETE_EXISTING_BACKUPS_FAILED);
    public const string ARTIFACT_MANAGEMENT_BACKUP_STEP_CREATE_DIRECTORY_FAILED = nameof(ARTIFACT_MANAGEMENT_BACKUP_STEP_CREATE_DIRECTORY_FAILED);
    public const string ARTIFACT_MANAGEMENT_BACKUP_ARTIFACT_UPLOAD_FAILED = nameof(ARTIFACT_MANAGEMENT_BACKUP_ARTIFACT_UPLOAD_FAILED);

    public const string ARTIFACT_MANAGEMENT_EXPORT_STEP_CREATE_DESTINATION_FAILED = nameof(ARTIFACT_MANAGEMENT_EXPORT_STEP_CREATE_DESTINATION_FAILED);
    public const string ARTIFACT_MANAGEMENT_EXPORT_STEP_DELETE_EXISTING_EXPORTS_FAILED = nameof(ARTIFACT_MANAGEMENT_EXPORT_STEP_DELETE_EXISTING_EXPORTS_FAILED);
    public const string ARTIFACT_MANAGEMENT_EXPORT_STEP_CREATE_DIRECTORY_FAILED = nameof(ARTIFACT_MANAGEMENT_EXPORT_STEP_CREATE_DIRECTORY_FAILED);
    public const string ARTIFACT_MANAGEMENT_EXPORT_ARTIFACT_UPLOAD_FAILED = nameof(ARTIFACT_MANAGEMENT_EXPORT_ARTIFACT_UPLOAD_FAILED);

    public const string ARTIFACT_MANAGEMENT_IMPORT_EXCEPTION = nameof(ARTIFACT_MANAGEMENT_IMPORT_EXCEPTION);
    public const string ARTIFACT_MANAGEMENT_IMPORT_STEP_BACKUP_FAILED = nameof(ARTIFACT_MANAGEMENT_IMPORT_STEP_BACKUP_FAILED);
    public const string ARTIFACT_MANAGEMENT_IMPORT_STEP_PAUSE_FAILED = nameof(ARTIFACT_MANAGEMENT_IMPORT_STEP_PAUSE_FAILED);
    public const string ARTIFACT_MANAGEMENT_IMPORT_STEP_DOMAIN_VALIDATION_FAILED = nameof(ARTIFACT_MANAGEMENT_IMPORT_STEP_DOMAIN_VALIDATION_FAILED);
    public const string ARTIFACT_MANAGEMENT_IMPORT_STEP_DOWNLOAD_ARTIFACT_FAILED = nameof(ARTIFACT_MANAGEMENT_IMPORT_STEP_DOWNLOAD_ARTIFACT_FAILED);
    public const string ARTIFACT_MANAGEMENT_IMPORT_STEP_DELETE_DATA_FAILED = nameof(ARTIFACT_MANAGEMENT_IMPORT_STEP_DELETE_DATA_FAILED);
    public const string ARTIFACT_MANAGEMENT_IMPORT_STEP_EXTRACT_FAILED = nameof(ARTIFACT_MANAGEMENT_IMPORT_STEP_EXTRACT_FAILED);

    public const string ARTIFACT_MANAGEMENT_REVERT_TO_BACKUP_STEP_DOMAIN_VALIDATION_FAILED = nameof(ARTIFACT_MANAGEMENT_REVERT_TO_BACKUP_STEP_DOMAIN_VALIDATION_FAILED);
    public const string ARTIFACT_MANAGEMENT_REVERT_TO_BACKUP_STEP_DOWNLOAD_ARTIFACT_FAILED = nameof(ARTIFACT_MANAGEMENT_REVERT_TO_BACKUP_STEP_DOWNLOAD_ARTIFACT_FAILED);
    public const string ARTIFACT_MANAGEMENT_REVERT_TO_BACKUP_STEP_DELETE_DATA_FAILED = nameof(ARTIFACT_MANAGEMENT_REVERT_TO_BACKUP_STEP_DELETE_DATA_FAILED);
    public const string ARTIFACT_MANAGEMENT_REVERT_TO_BACKUP_STEP_EXTRACT_FAILED = nameof(ARTIFACT_MANAGEMENT_REVERT_TO_BACKUP_STEP_EXTRACT_FAILED);
    public const string ARTIFACT_MANAGEMENT_REVERT_TO_BACKUP_EXCEPTION = nameof(ARTIFACT_MANAGEMENT_REVERT_TO_BACKUP_EXCEPTION);
    
}
