FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS runtime
WORKDIR /app
ENV BUILD_CONFIGURATION Release
COPY src/EventHorizon.Game.Server.Zone/bin/${BUILD_CONFIGURATION}/net5.0/publish/. ./
ENTRYPOINT ["dotnet", "EventHorizon.Game.Server.Zone.dll"]